### ISSUE TITLE
Todo Create 기능

### ISSUE THREAD

**Issue by muffin9** [suuzin/todo-list#11]
TODO CREATE (Jinnie & Muffin)

  - [x] 버튼 마우스 오버시 색상 변경
  - [x] 버튼 클릭 시 카드 생성
  - [x] 카드가 렌더링된 상태인데 + 버튼 한 번더 클릭시 카드 제거
  - [x] 취소 버튼 클릭시 카드 제거
  - [ ] 내용이 입력될시만 등록버튼 활성화 + 내용없을 시 등록버튼 비활성화
    - input addeventListener 에서 `value 값` 유무에 따라 활성화 여부 체크
    - 버튼속성에 `disable 속성` 추가하면 비활성화 버튼으로 됨
  - [ ] 내용 입력 후 등록시 카드가 등록되고, 해당 카드 제거
    - 전체 todo를 관리하는 todos 배열에 카드가 등록
    - 서버 반영은 차후에...
    - 해당 카드 remove.
  - [ ] 글자수 제한 500자 이내
  - [ ] 글의 길이에 맞춰 박스가 아래로 늘어나도록 구현 + input height값도 함께 늘어난다.
    - div태그로 input태그처럼 구현? input(hidden 속성)을 사용 -> value만 관리하는 녀석, div가 view를 관리하는 녀석
  - [ ] 카드 등록 완료 후 해당 Column에 맞는 Count 증가
    - TodoColumn 클래스에서 할지? TodoCount 클래스 만들어서 할지 고민
    - count data를 column 마다 계속 가지고 있어서 카드 등록 시 count + 1 해주기
