### ISSUE TITLE
TODO UPDATE

### ISSUE THREAD

**Issue by muffin9** [suuzin/todo-list#12]
- [x] TODO UPDATE (Jinnie)
  - [x] 카드 더블클릭시 수정이 가능한 상태로 변경
    - dbclick addeventlistener 에서 수정 변경 가능하도록 구현
    - ~state 값을 두어서 현재 카드가 수정상태인지 판별~
  - [x] 취소 버튼 클릭시 수정 취소. 변경사항 반영 X
    - ~수정 여부의 데이터 state값을 false로 하여 카드 원복~
  - [x] 내용을 모두 삭제시 수정 버튼 비활성화, 내용을 수정한 후 수정버튼 클릭시 변경사항 반영
    - content 내용이 없을 시 버튼 비활성화
