### ISSUE TITLE
TODO DELETE

### ISSUE THREAD

**Issue by muffin9** [suuzin/todo-list#13]
- [x] TODO DELETE (Jinnie)

  - [x] 칼럼 X 버튼은 마우스 오버시에만 색변경, 클릭은 아무 이벤트 X
  - [x] 카드 X 버튼 마우스 오버시 카드색 변경
  - [x] 카드 X 버튼 삭제 팝업창이 띄워지도록 구현
  - [x] 알럿창 취소 버튼 클릭시 삭제 팝업창 닫힘
  - [x] 알럿창 삭제 버튼 클릭시 해당 카드 삭제 + 삭제 팝업창 닫힘
  - [x] UI 마무리
