### ISSUE TITLE
TODO MENU 

### ISSUE THREAD

**Issue by muffin9** [suuzin/todo-list#14]
- [ ] MENU 버튼 클릭 시 화면 노출 (Muffin)

  - [x] 애니메이션 효과 추가
  - [x] X 버튼 클릭 시 MENU 화면 없어짐
  - [x] 사용자 액션 최신순으로 보여주기
  - [x] 기록이 많아지면 스크롤 생성
  - [x] 이동, 추가, 수정, 삭제시 Alarm Class가 알 수 있도록 TodoNotice 클래스 구현
  - [x] title, content, status 값은 bold 처리해서 렌더링
  - [x] 모든 화면 크기에서 동일하게 동작되도록 코드 수정
  - [ ] 코드 리팩토링
