### ISSUE TITLE
TODO READ

### ISSUE THREAD

**Issue by muffin9** [suuzin/todo-list#19]
- [x] TODO READ (Jinnie & Muffin)

  - [x] TODO dummy data 화면에 뿌리기
  - [x] client todos 배열 화면에 뿌리기
