### ISSUE TITLE
todo create 기능

### ISSUE THREAD

**Issue by suuzin** [suuzin/todo-list#9]
TODO CREATE (Jinnie & Muffin)

  - [x] 버튼 마우스 오버시 색상 변경
  - [x] 버튼 클릭 시 카드 생성
  - [x] 카드가 렌더링된 상태인데 + 버튼 한 번더 클릭시 카드 제거
  - [x] 취소 버튼 클릭시 카드 제거
  - [x] 내용이 입력될시만 등록버튼 활성화 + 내용없을 시 등록버튼 비활성화
    - input addeventListener 에서 `value 값` 유무에 따라 활성화 여부 체크
    - 버튼속성에 `disable 속성` 추가하면 비활성화 버튼으로 됨
  - [x] 내용 입력 후 등록시 카드가 등록되고, 해당 카드 제거
    - 전체 todo를 관리하는 todos 배열에 카드가 등록
    - 🤔 시간 데이터 추가 필요
    - 서버 반영은 차후에...
    - ~해당 카드 remove.~
  - [x] 글자수 제한 500자 이내
  - [x] 글의 길이에 맞춰 박스가 아래로 늘어나도록 구현 + input height값도 함께 늘어난다.
    - ~div태그로 input태그처럼 구현? input(hidden 속성)을 사용 -> value만 관리하는 녀석, div가 view를 관리하는 녀석~
    - textarea 태그 사용
